[tool.poetry]
name = "aith_mlops"
version = "0.1.0"
description = ""
authors = ["Semyon W232 <lukinsemyon@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.3.0"
numpy = "^2.3.0"
scikit-learn = "^1.7.0"
xgboost = "^3.0.2"
lakefs = "^0.11.1"
jupyterlab = "^4.4.3"
lakefs-sdk = "^1.60.0"
clearml = "^2.0.0"
catboost = "^1.2.8"
optuna = "^4.4.0"


[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
isort = "^6.0.1"
flake8 = "^7.2.0"
pre-commit = "^4.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
